### ISSUE TITLE
Columns with a mix of populated and empty cells are being skipped entirely

### ISSUE THREAD

**Issue by luckman212** [cujarrett/markdown-tables#23]
Thank you for this very useful tool 👍 

If I have an XLSX file with the following data (sample: [data1.xlsx](https://github.com/cujarrett/markdown-tables/files/5876059/data1.xlsx)):

| Foo | Bar | Baz |
|:--- |:--- |:--- |
| A   |     | C   |
| 1   | 2   | 3   |
| x   | y   | z   |

When converted with this tool (v2.4.0) the result is

| Foo | Baz |
|-----|-----|
| A   | C   |
| 1   | 3   |
| x   | z   |

The entire **Bar** column is completely destroyed. Is this avoidable?

**Comment by cujarrett** [comment]
Thanks for the support @luckman212 🙏 

I'll look into a fix.

**Comment by cujarrett** [comment]
Fixed in `v2.4.1` @luckman212 , thanks for sharing 🙌 

If you see any issues please let me know.

**Comment by luckman212** [comment]
Awesome! 🎉  Yes, confirmed it's working now, thank you so much!

(how this project doesn't have more ★s is a mystery to me...)
